defaults: &defaults
    working_directory: /wp-e2e-tests
    docker:
      - image: automattic/wp-e2e-tests:0.0.7
        environment:
                JETPACKHOST: CI
                NODE_ENV: test
version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Clone wp-e2e-tests repo!
          command: |
                  cd /
                  git clone https://github.com/Automattic/wp-e2e-tests.git
                  cd /wp-e2e-tests
                  git checkout origin/try/jetpack-failed-tests-cleanup-magellan
      - restore_cache:
          key: << checksum "package.json" >>
      - run: source $HOME/.nvm/nvm.sh && npm install
      - save_cache:
          paths:
            - /wp-e2e-tests/node_modules
          key: << checksum "package.json" >>
      - persist_to_workspace:
          root: /wp-e2e-tests
          paths:
            - .
  test:
    <<: *defaults
    parallelism: 2
    steps:
      - attach_workspace:
          at: /wp-e2e-tests
      - run:
          name: Randomize spec execution order
          command: ./scripts/randomize.sh specs
      - run:
          name: Run e2e tests
          command: xvfb-run ./run.sh -R -j -H CI -p
      - store_test_results:
          path: reports/
      - store_artifacts:
          path: reports/
      - store_artifacts:
          path: screenshots/
workflows:
  version: 2
  build_test:
    jobs:
      - build:
          filters:
             branches:
                only:
                  - master
                  - /.*e2e.*/
      - test:
          requires:
            - build
